### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Reality-Dev** [gualtierofrigerio/SwiftUIScroll#4]
Are others allowed to use this code? Please add a license to this repository.

**Comment by gualtierofrigerio** [comment]
I distributed the code via SPM here https://github.com/gualtierofrigerio/GFRefreshableScrollView
but I can add the MIT license to this one as well

**Comment by Reality-Dev** [comment]
Yes, in general the repository for any Swift Package needs a license for other developers to know how they are allowed to use it. Thank you so much for adding one!
